language: objective-c
osx_image: xcode7.3
env:
  global:
    - CONFIG=opt
    - TEST=objc
    - JOBS=1
before_install:
  - brew install gflags
  - gem which cocoapods
  - pod --version
  - gem install cocoapods -v '1.0.0.rc.1' --user-install
  - gem which cocoapods
  - pod --version
install:
  - make grpc_objective_c_plugin
  - pushd src/objective-c/tests
  - pod install
  - popd
before_script:
  - make interop_server
  - bins/$CONFIG/interop_server --port=5050 &
  - bins/$CONFIG/interop_server --port=5051 --use_tls &
xcode_workspace: src/objective-c/tests/Tests.xcworkspace
xcode_scheme: AllTests
xcode_sdk: iphonesimulator9.3
notifications:
  email: false
