language: objective-c
osx_image: xcode7.3
env:
  global:
    - CONFIG=opt
    - TEST=objc
    - JOBS=1
before_install:
  - gem which cocoapods
  - pod --version
  - gem uninstall cocoapods -a
  - gem install cocoapods -v '1.0.0.rc.1'
  - gem which cocoapods
  - pod --version
  - brew update && brew reinstall --HEAD xctool || true
  - brew install gflags
install:
  - pushd third_party/protobuf
  - git checkout 79a23c435c4862d0c7af3c2740662104c77171dc
  - popd
  - make grpc_objective_c_plugin
  - pushd src/objective-c/tests
  - pod install
  - popd
before_script:
  - make interop_server
  - bins/$CONFIG/interop_server --port=5050 &
  - bins/$CONFIG/interop_server --port=5051 --use_tls &
xcode_workspace: src/objective-c/tests/Tests.xcworkspace
xcode_scheme: AllTests
xcode_sdk: iphonesimulator9.3
notifications:
  email: false
