language: objective-c
before_install:
  - curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.3.3.tar.bz2
  - tar xf MacPorts-2.3.3.tar.bz2
  - cd MacPorts-2.3.3/
  - ./configure
  - make
  - sudo make install
  - sudo /opt/local/bin/port install gflags
env:
  global:
    - CONFIG=opt
    - TEST=objc
    - JOBS=1
script:
  - ./tools/run_tests/run_tests.py -l $TEST -t -j $JOBS -c $CONFIG -s 4.0
notifications:
  email: false
