language: objective-c
osx_image: xcode7.1
cache:
  cocoapods: true
  # For some reason listing ccache doesn't validate
  directories:
    - /Users/travis/.ccache
env:
  global:
    - CONFIG=opt
    - TEST=objc
    - JOBS=1
before_install:
  - brew install ccache
  - which clang
  - export PATH=/usr/local/opt/ccache/libexec:$PATH
  - which clang
  - export CC=`which clang`
  - echo $CC
  # Show ccache stats:
  - ccache -s
  - brew install gflags
  # Pod install does this too, but we don't want the output.
  - pod repo update --silent
install:
  - ccache -p | grep "cache_dir\s\=\s.*$" -o | cut -c 13-
  - echo $HOME
  - [ -d /Users/travis/.ccache ]
  - make grpc_objective_c_plugin
  - make interop_server
  - pushd src/objective-c/tests
  # Needs to be verbose, or otherwise OpenSSL's prepare_command makes Travis
  # time out:
  - pod install --verbose
  - popd
before_script:
  - bins/$CONFIG/interop_server --port=5050 &
  - bins/$CONFIG/interop_server --port=5051 --use_tls &
xcode_workspace: src/objective-c/tests/Tests.xcworkspace
xcode_scheme: AllTests
xcode_sdk: iphonesimulator9.1
notifications:
  email: false
