source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

if ENV['USE_FRAMEWORKS'] == 'YES' then
  use_frameworks!
end

def shared_pods
  pod 'Protobuf', :path => "../../../third_party/protobuf"
  pod 'BoringSSL', :podspec => ".."

  pod 'RxLibrary', :path => "../../.."
  pod 'gRPC-Core', :path => "../../.."
  pod 'gRPC', :path => "../../.."
  pod 'ProtoRPC', :path => "../../.."

  pod 'RemoteTestClient', :path => "RemoteTestClient"
end

target 'AllTests' do
  shared_pods
end

target 'SelfContainedTests' do
  shared_pods
end
