source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'Tests' do
  pod 'Protobuf', :path => "../../../third_party/protobuf"
  pod 'BoringSSL', :podspec => ".."
  pod 'gRPC', :path => "../../.."
  pod 'RemoteTestClient', :path => "RemoteTestClient"
end

# target 'AllTests' do
# end

# target 'RxLibraryUnitTests' do
# end

# target 'InteropTestsRemote' do
# end

# target 'InteropTestsLocalSSL' do
# end

# target 'InteropTestsLocalCleartext' do
# end
